name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 2

jobs:
  test:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [16, 18, 20]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run Coveralls
        uses: coverallsapp/github-action@v2
        if: matrix.node == 20
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
